version: 2

before:
  hooks:
    - go run ./cmd/prepare-xgo-runtime

builds:
  - id: xgols
    main: .
    binary: xgols
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - id: xgo-runtime
    dir: .runtime/xgo
    main: ./cmd/xgo
    binary: xgo
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - ids:
      - xgols
      - xgo-runtime
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "xgols_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - src: .runtime/xgo/**/*
        dst: xgo-runtime
      - src: .runtime/xgo/go.mod
        dst: xgo-runtime
        strip_parent: true
      - src: .runtime/xgo/go.sum
        dst: xgo-runtime
        strip_parent: true
      - src: .runtime/xgo/VERSION
        dst: xgo-runtime
        strip_parent: true

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
